define("packages", [

    "multiversion/jquery-master",
    "multiversion/underscore-master",
    "CoMa",
    "base/Cache",
    "base/Collection",
    "base/Controller",
    "base/DomModel",
    "base/Events",
    "base/Model",
    "common/Controller",
    "components/admin/CacheRefresh",
    "components/admin/Warranties",
    "components/controller/Area",
    "components/controller/Component",
    "components/controllerBrowser/Controller",
    "components/dialog/EditDialog",
    "components/dialog/EditComponent",
    "components/dialog/EditArea",
    "components/dialog/FormDialog",
    "components/dialog/GlobalProperties",
    "components/dialog/PageProperties",
    "components/dialog/SelectComponent",
    "components/field/CodeEditor",
    "components/field/DateSelect",
    "components/field/LinkSelect",
    "components/field/MediaSelect",
    "components/field/ColorPicker",
    "components/Controller",
    "components/ControllerBrowser",
    "components/Logs",
    "components/Modal",
    "components/PageManager",
    "components/TabContainer",
    "components/MultipleValues",
    "components/EditableProperty",
    "services/history/Callback",
    "services/history/Entry",
    "services/history",
    "services/parser",
    "services/logs",
    "services/random",
    "services/url",
    "services/dragObserver",
    "utils/Fullscreen",

    "main",
    "config"

]);

